<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.0 (Python 3.12.2 on win32)" generated="2024-03-18T01:34:29.672598" rpa="false" schemaversion="5">
<suite id="s1" name="HepsiburadaTest" source="C:\Users\Public\robot_Framework\tests\HepsiburadaTest.robot">
<test id="s1-t1" name="Basarili Hepsiburada baglantisi" line="9">
<kw name="Hepsiburada anasayfasina git">
<msg time="2024-03-18T01:34:30.527872" level="FAIL">No keyword with name 'Hepsiburada anasayfasina git' found.</msg>
<status status="FAIL" start="2024-03-18T01:34:30.527872" elapsed="0.001011">No keyword with name 'Hepsiburada anasayfasina git' found.</status>
</kw>
<status status="FAIL" start="2024-03-18T01:34:30.512927" elapsed="0.015956">No keyword with name 'Hepsiburada anasayfasina git' found.</status>
</test>
<status status="FAIL" start="2024-03-18T01:34:29.681603" elapsed="0.848279"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="HepsiburadaTest">HepsiburadaTest</stat>
</suite>
</statistics>
<errors>
<msg time="2024-03-18T01:34:30.509908" level="ERROR">Error in file 'C:\Users\Public\robot_Framework\tests\HepsiburadaTest.robot' on line 3: Error in file 'C:\Users\Public\robot_Framework\pages\hepsiburadaPage.robot' on line 28: Resource file with 'Test Cases' section is invalid.</msg>
</errors>
</robot>
